### ISSUE TITLE
`pull_request.synchronize` is not supported by this action.

### ISSUE THREAD

**Issue by ghost** [TimonVS/pr-labeler-action#1]
Hi Timon! I'm having difficulties using this action. I keep receiving this error.

```
✖  error     Event `pull_request.synchronize` is not supported by this action.
```

I followed the instructions in the readme. Here's my workflow

```
workflow "Add label to PR" {
  resolves = "PR Labeler"
  on = "pull_request"
}

action "PR Labeler" {
  uses = "TimonVS/pr-labeler@master"
  secrets = ["GITHUB_TOKEN"]
}
```

**Comment by TimonVS** [comment]
Hey @rv-asilva, sorry for my late reply. Am I right in assuming that even though you get the error the Action still works?
The reason you're getting this error is because GitHub Actions doesn't yet let me specify for which specific action of the [pull request event](https://developer.github.com/v3/activity/events/types/#pullrequestevent) the Action should be ran, instead the Action will run everytime the pull request event is triggered (e.g. review requested, new commits pushed, etc.) Instead I'm using [actions-toolkit](https://github.com/JasonEtco/actions-toolkit) which lets me specify that the Action should only run for `pull_request.opened`, for all other PR events it will log an error to the console (https://github.com/JasonEtco/actions-toolkit/blob/bb11106fe8024e39c3341d5c2bd78acd28958e31/src/index.ts#L267). I've already contacted GitHub about this issue, but for a short term solution I propose to add a filter action in the workflow that will filter all PR events except for `pull_request.opened`. I will look into this soon, I'll keep you updated in this issue :)

**Comment by TimonVS** [comment]
There appears to already be an action to filter by action type, the following workflow should solve the issue:

```
workflow "Add label to PR" {
  on = "pull_request"
  resolves = "PR Labeler"
}

action "PR opened filter" {
  uses = "actions/bin/filter@master"
  args = "action opened"
}

action "PR Labeler" {
  needs = "PR opened filter"
  uses = "TimonVS/pr-labeler@master"
  secrets = ["GITHUB_TOKEN"]
}
```

**Comment by TimonVS** [comment]
Not relevant anymore with the release of Actions V2 as it allows us to only run the Action when a PR is opened ([see usage example](https://github.com/TimonVS/pr-labeler-action#usage)).
